Annonces_allVente:
  path:     /all_Vente
  defaults: { _controller: AnnonceBundle:FAnnonceV:index }
show_annoncev/:
  path:     /Show_v/{id}
  defaults: { _controller: AnnonceBundle:FAnnonceV:show }
Ann_user/:
  path:     /foruser/{id}
  defaults: { _controller: AnnonceBundle:FAnnonceV:showuser }
delete_Fannoncev/:
  path:     /deleteFV/{id}
  defaults: { _controller: AnnonceBundle:FAnnonceV:delete }
FAddVente:
  path:     /Add_Annonce
  defaults: { _controller: AnnonceBundle:FAnnonceV:Ajouter }
update_annoncev/:
  path:     /updatev/{id}
  defaults: { _controller: AnnonceBundle:FAnnonceV:edit }
Annonces_allEchanges:
  path:     /all_Echange
  defaults: { _controller: AnnonceBundle:FAnnonceE:index }
Ann_userE/:
  path:     /foruserE/{id}
  defaults: { _controller: AnnonceBundle:FAnnonceE:showuser }
show_annonceE/:
  path:     /Show_E/{id}
  defaults: { _controller: AnnonceBundle:FAnnonceE:show }
update_annoncee/:
  path:     /updatee/{id}
  defaults: { _controller: AnnonceBundle:FAnnonceE:edit }
delete_FannonceE/:
  path:     /deleteFE/{id}
  defaults: { _controller: AnnonceBundle:FAnnonceE:delete }
FAddEchange:
  path:     /Add_AnnonceE
  defaults: { _controller: AnnonceBundle:FAnnonceE:Ajouter }
Annonces_allLocation:
  path:     /all_Location
  defaults: { _controller: AnnonceBundle:FAnnoncel:index }
show_annoncel/:
  path:     /Show_l/{id}
  defaults: { _controller: AnnonceBundle:FAnnoncel:show }
Ann_userl/:
  path:     /foruserl/{id}
  defaults: { _controller: AnnonceBundle:FAnnoncel:showuser }
delete_annonceLoc/:
  path:     /deleteLoc/{id}
  defaults: { _controller: AnnonceBundle:FAnnoncel:delete }
update_annonceLoc/:
  path:     /updateLoc/{id}
  defaults: { _controller: AnnonceBundle:FAnnoncel:edit }
FAddLocation:
  path:     /Add_AnnonceLoc
  defaults: { _controller: AnnonceBundle:FAnnoncel:Ajouter }