annonce_homepage:
    path:     /
    defaults: { _controller: AnnonceBundle:Annoncev:index }
edit_annonce/:
    path:     /edit/{id}
    defaults: { _controller: AnnonceBundle:Annoncev:edit }
delete_annonce/:
    path:     /delete/{id}
    defaults: { _controller: AnnonceBundle:Annoncev:delete }
Ajouter_annonce/:
    path:     /Ajouter_annonce
    defaults: { _controller: AnnonceBundle:Annoncev:ajouter }
afficher_annonce/:
    path:     /Afficher/{id}
    defaults: { _controller: AnnonceBundle:Annoncev:show }
Test_annonce/:
    path:     /Test_annonce
    defaults: { _controller: AnnonceBundle:Annoncev:test }
annonce_Echange:
    path:     /Echange
    defaults: { _controller: AnnonceBundle:AnnonceE:index }
edit_annonceE/:
    path:     /editE/{id}
    defaults: { _controller: AnnonceBundle:AnnonceE:edit }
delete_annonceE/:
    path:     /deleteE/{id}
    defaults: { _controller: AnnonceBundle:AnnonceE:delete }
Ajouter_annonceE/:
    path:     /AjouterE_annonce
    defaults: { _controller: AnnonceBundle:AnnonceE:ajouter }
afficher_annonceE/:
    path:     /AfficherE/{id}
    defaults: { _controller: AnnonceBundle:AnnonceE:show }
annonce_Location:
    path:     /Location
    defaults: { _controller: AnnonceBundle:AnnonceL:index }
edit_annonceL/:
    path:     /editL/{id}
    defaults: { _controller: AnnonceBundle:AnnonceL:edit }
delete_annonceL/:
    path:     /deleteL/{id}
    defaults: { _controller: AnnonceBundle:AnnonceL:delete }
Ajouter_annonceL/:
    path:     /AjouterL_annonce
    defaults: { _controller: AnnonceBundle:AnnonceL:ajouter }
afficher_annonceL/:
    path:     /AfficherL/{id}
    defaults: { _controller: AnnonceBundle:AnnonceL:show }
Statistique:
    path:     /Statistique
    defaults: { _controller: AnnonceBundle:Statistique:index }
Importer_module:
    path:     /upload
    defaults: { _controller: AnnonceBundle:Upload:index }
Annonces_all:
    path:     /all
    defaults: { _controller: AnnonceBundle:annonce:index }
Annonces_allVente:
    path:     /all_Vente
    defaults: { _controller: AnnonceBundle:FAnnonceV:index }
show_annoncev/:
    path:     /Show_v/{id}
    defaults: { _controller: AnnonceBundle:FAnnonceV:show }
Ann_user/:
    path:     /foruser/{id}
    defaults: { _controller: AnnonceBundle:FAnnonceV:showuser }
delete_Fannoncev/:
    path:     /deleteFV/{id}
    defaults: { _controller: AnnonceBundle:FAnnonceV:delete }
FAddVente:
    path:     /Add_Annonce
    defaults: { _controller: AnnonceBundle:FAnnonceV:Ajouter }
update_annoncev/:
    path:     /updatev/{id}
    defaults: { _controller: AnnonceBundle:FAnnonceV:edit }
Annonces_allEchanges:
    path:     /all_Echange
    defaults: { _controller: AnnonceBundle:FAnnonceE:index }
Ann_userE/:
    path:     /foruserE/{id}
    defaults: { _controller: AnnonceBundle:FAnnonceE:showuser }
show_annonceE/:
    path:     /Show_E/{id}
    defaults: { _controller: AnnonceBundle:FAnnonceE:show }
update_annoncee/:
    path:     /updatee/{id}
    defaults: { _controller: AnnonceBundle:FAnnonceE:edit }
delete_FannonceE/:
    path:     /deleteFE/{id}
    defaults: { _controller: AnnonceBundle:FAnnonceE:delete }
FAddEchange:
    path:     /Add_AnnonceE
    defaults: { _controller: AnnonceBundle:FAnnonceE:Ajouter }
Annonces_allLocation:
    path:     /all_Location
    defaults: { _controller: AnnonceBundle:FAnnoncel:index }
show_annoncel/:
    path:     /Show_l/{id}
    defaults: { _controller: AnnonceBundle:FAnnoncel:show }
Ann_userl/:
    path:     /foruserl/{id}
    defaults: { _controller: AnnonceBundle:FAnnoncel:showuser }
delete_annonceLoc/:
    path:     /deleteLoc/{id}
    defaults: { _controller: AnnonceBundle:FAnnoncel:delete }
update_annonceLoc/:
    path:     /updateLoc/{id}
    defaults: { _controller: AnnonceBundle:FAnnoncel:edit }
FAddLocation:
    path:     /Add_AnnonceLoc
    defaults: { _controller: AnnonceBundle:FAnnoncel:Ajouter }