fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
test:
    resource: "@TestBundle/Resources/config/routing.yml"
    prefix:   /Test
app:
    resource: '@AppBundle/Controller/'
    type: annotation
Admin:
    resource: "@AnnonceBundle/Resources/config/admin.yml"
    prefix:   /admin