fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
map:
    resource: "@MapBundle/Resources/config/routing.yml"
    prefix:   /Map
app:
    resource: '@AppBundle/Controller/'
    type: annotation
Admin:
    resource: "@AnnonceBundle/Resources/config/admin.yml"
    prefix:   /admin