fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
app:
    resource: '@AppBundle/Controller/'
    type: annotation
Admin:
    resource: "@AnnonceBundle/Resources/config/admin.yml"
    prefix:   /admin
Front:
    resource: "@AnnonceBundle/Resources/config/front.yml"
    prefix:   /front
Test:
    resource: "@TestBundle/Resources/config/routing.yml"
    prefix:   /Test