<?php

namespace AnnonceBundle\Repository;

/**
 * moduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class moduleRepository extends \Doctrine\ORM\EntityRepository
{
}
